spring:
  application:
    name: message
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/message
    username: nrin31266
    password: 16092005
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "HDKdDVDEpABtpunTzN2QM2pbmVzDP5jht6WGykegNKgsKDVdDlbzFVmU1vDOVOHV"


server:
  port: 8080
  servlet:
    context-path: /api
